language: node_js
node_js:
  - 12 # uses version 12
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "deployment-exercise-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: light-ward
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: k58l+SrLWPIq86cywcxKqZlAbsl3O7gXX3/lnNtGXDBQamtr8LebXqyMWiJFs2JXHmrZgR38DpYsYHuodXxK87FStjI3LLH3nkQPRucUM+HYA0YAeQrvTsw+HJILRk+G2fPaM/WQ5gTkRP0wUNrCBUA7aXfdeaF5l3f7/aFohf/G1Qa8NbORiIR4XmMgJAQ6FUBa/LrC4x+cQ4BrjitBxgMGf+utmDxRXWUUyS/DcFzKQKQ/wohuGeVUmzmdynYuBtOjmMA3mQNlEiT9pCM2IilU+Dvj+DrfjoYHwXwtVr1wP31SpNH0g5i4pUuAlPQy+q/4joVHsnHZ3gQPfYtpOA0ETXqbpgNozCP8Pz5JH2h97cS7orDxRERi8jeusDwf+uTaSUg+mJr+hGyc4v+ISpMdnogaEGb+RgKrlvqrO+AHmm3Y0QvVIvZ0gMbP3BWiLtQUNK3pxwE0Lp3zLdD2Ge0uK/fnKHRJkM6NNpCNYNSlaC6i6UyNpIB8RJQTwHKhGT86/53/CuiZIFz7IwibIdWzp4YY8zQR4zHVInfxwn0O0KSuykr5owbhiaGQcEDhU6u8VyhHPYtRrO69lG5e+RMst7FUooxhs/i4KtWReIKgBCzSLkB/shg7WQEVs035e42ZMjb4MoSkQnWkW/UeC1J2mIxAZoIoxFazz+AGXuU=
